import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    settings: {
      'import/resolver': {
        typescript: {
          project: ['./tsconfig.json'],
          alwaysTryTypes: true,
        },
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      },
    },
    rules: {
      'array-callback-return': ['error', { checkForEach: true }],
      'comma-dangle': ['error', 'always-multiline'],
      'default-case-last': 'error',
      'dot-notation': ['error', { allowKeywords: true }],
      eqeqeq: ['error', 'smart'],
      'no-else-return': ['error', { allowElseIf: false }],
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-proto': 'error',
      'no-script-url': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'object-shorthand': ['error', 'always'],
      'one-var': ['error', 'never'],
      'prefer-const': ['error', { destructuring: 'all' }],
      'prefer-object-spread': 'error',
      'prefer-template': 'error',
      radix: ['error', 'as-needed'],
      yoda: ['error', 'never'],
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/newline-after-import': ['error', { count: 1 }],
      'import/no-useless-path-segments': ['error', { noUselessIndex: true }],
      'import/no-absolute-path': 'error',
      'import/no-self-import': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-webpack-loader-syntax': 'error',
      'import/no-unresolved': 'error',
      'import/extensions': [
        'error',
        'ignorePackages',
        {
          js: 'never',
          jsx: 'never',
          ts: 'never',
          tsx: 'never',
        },
      ],
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object', 'type'],
          'newlines-between': 'always',
        },
      ],
      'react/jsx-no-duplicate-props': ['error', { ignoreCase: false }],
      'react/jsx-filename-extension': ['error', { extensions: ['.tsx'] }],
      'react/jsx-tag-spacing': [
        'error',
        {
          closingSlash: 'never',
          beforeSelfClosing: 'never',
          afterOpening: 'never',
          beforeClosing: 'allow',
        },
      ],
      'react/jsx-boolean-value': ['error', 'never'],
      'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
      'react/jsx-no-useless-fragment': 'error',
      'react/self-closing-comp': ['error', { component: true, html: true }],
      'react/require-default-props': 'off',
      'react/forbid-prop-types': 'off',
      'react/function-component-definition': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/destructuring-assignment': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/no-multi-comp': 'error',
      'react/no-unused-prop-types': 'error',
      'react/no-children-prop': 'off',
      'react/jsx-no-bind': 'off',
      'react/default-props-match-prop-types': 'off',
      'react/prop-types': 'off',
      'react/no-danger': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      'jsx-a11y/no-noninteractive-element-interactions': 'error',
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'computed-property-spacing': ['error', 'never'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'space-infix-ops': 'error',
      'space-before-blocks': ['error', 'always'],
      'spaced-comment': ['error', 'always', { markers: ['/'] }],
      'no-trailing-spaces': 'error',
      indent: ['error', 2, { SwitchCase: 1 }],
      'no-mixed-operators': [
        'error',
        {
          groups: [
            ['&', '|', '^', '~', '<<', '>>', '>>>'],
            ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
            ['&&', '||'],
            ['in', 'instanceof'],
          ],
          allowSamePrecedence: false,
        },
      ],
      'no-var': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'template-curly-spacing': ['error', 'never'],
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'block-spacing': ['error', 'always'],
      'no-tabs': 'error',
      'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: ['multiline-const', 'multiline-let'], next: '*' },
        { blankLine: 'always', prev: '*', next: ['multiline-const', 'multiline-let'] },
        { blankLine: 'never', prev: ['singleline-let', 'singleline-const'], next: ['singleline-let', 'singleline-const'] },
        { blankLine: 'always', prev: '*', next: 'function' },
      ],
      curly: ['error', 'multi-line'],
      'object-curly-newline': ['error', { consistent: true }],
      'no-nested-ternary': 'error',
      'max-len': ['error', { code: 130 }],
      'arrow-parens': ['error', 'as-needed'],
      'no-param-reassign': 'error',
      'no-underscore-dangle': 'off',
      'no-prototype-builtins': 'off',
      'prefer-destructuring': 'off',
      'no-restricted-exports': ['error', { restrictedNamedExports: ['off'] }],
      'max-classes-per-file': ['error', 1],
      'class-methods-use-this': 'error',
      'no-multi-assign': 'error',
      'consistent-return': 'off',
      'func-names': 'off',
      'eol-last': ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      semi: ['error', 'always'],
      'jsx-quotes': ['error', 'prefer-single'],
    },
  },
  globalIgnores([
    '**/.next/**',
    '**/.cloudflare/**',
    '**/.vinext/**',
    '**/dist/**',
    '**/out/**',
    '**/build/**',
    '**/next-env.d.ts',
    '**/node_modules/**',
    '**/.turbo/**',
  ]),
]);

export default eslintConfig;
